### ISSUE TITLE
Caught exception executing task

### ISSUE THREAD

**Issue by elcamb** [soulj/PhenomeScape#1]
I'm running Phenomescape using a human network and a table of differentially expressed genes. I set up the analysis using p.value and fold change, but get these errors:
_(The first of the two repeats hundreds of times)_

 Improperly specified payload event with source: org.cytoscape.view.model.internal.table.CyTableViewImpl@795f68bb; with payload: null; with event type: class org.cytoscape.view.model.events.AddedRowViewsEvent
 Caught exception executing task.

Can you suggest how to avoid this error?
Thanks

**Comment by soulj** [comment]
Thanks for the error report. To help me narrow down the problem:

Are you able to run the analysis using the example data?
What version of Cytoscape are you using?  

PhenomeScape does seems to be failing with Cytoscape v3.9 but I’ve ran PhenomeScape using the example data with Cytoscape v3.8.2 successfully. I’ll take a look into why and release an updated version for the newest Cytoscape, but if you are using using Cytoscape v3.9 perhaps you can downgrade to v3.8 and try?

**Comment by elcamb** [comment]
Thanks, 
I'm indeed running cytoscape v3.9.1 and PhenomeScape fails to run also with the example data.
I would prefer not to downgrade at this stage but will consider it if needed in the future.
Look forward to the updated version!

**Comment by soulj** [comment]
The app should now be compatible with cytoscape v3.9. I've uploaded the new version to the app store. Thanks again for the bug report!

**Comment by elcamb** [comment]
Thanks so much, Jamie. It works perfectly now
